runtime: nodejs16
env: standard
service: anilkumar
handlers:
  - url: /(.*\.(html|css|js))
    static_files: build/\1
    upload: build/(.*\.(html|css|js))

  - url: /.*
    static_files: build/index.html
    upload: build/index.html